func doNoErr()
  println('On Error Resume Next') 
end
